# Prometheus configuration for ML service monitoring
# Comprehensive metrics collection for performance optimization

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'interview-ml-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # ML Server metrics
  - job_name: 'ml-server'
    static_configs:
      - targets: ['ml-server:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    
  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    
  # GPU metrics (if available)
  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['nvidia-gpu-exporter:9445']
    scrape_interval: 10s
    
  # Custom application metrics
  - job_name: 'interview-analysis'
    static_configs:
      - targets: ['ml-server:8001']
    metrics_path: '/metrics/custom'
    scrape_interval: 5s
    params:
      format: ['prometheus']

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"